GRID_SIZE = 40
PIXEL_SIZE = 16
INITIAL_SHEEPS = 50
INITIAL_WOLVES = 10
INITIAL_GRASS_COVERAGE = 0.3

SHEEP_INITIAL_ENERGY = 20
WOLF_INITIAL_ENERGY = 10
SHEEP_ENERGY_LOSS_PER_TURN = 1
WOLF_ENERGY_LOSS_PER_TURN = 2

GRASS_REGROWTH_TIME = 7
